name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pandas
  - matplotlib
  - jupyter-ai
  - langchain-openai
  - numpy
  - palmerpenguins
  - scikit-learn
  - plotly
  - seaborn
  - ipython
